'use client';

import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Printer, CheckCircle } from 'lucide-react';

interface ReceiptModalProps {
    isOpen: boolean;
    onClose: () => void;
    data: any;
}

export default function ReceiptModal({ isOpen, onClose, data }: ReceiptModalProps) {
    if (!isOpen || !data) return null;

    const handlePrint = () => {
        window.print();
    };

    return (
        <AnimatePresence>
            <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4 font-mono print:bg-white print:static print:p-0">
                <motion.div
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.9 }}
                    className="bg-white w-full max-w-sm rounded-none shadow-2xl p-0 overflow-hidden relative print:shadow-none print:w-full print:max-w-none"
                    onClick={(e) => e.stopPropagation()}
                >
                    {/* Close Button (Hidden on Print) */}
                    <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-black print:hidden">
                        <X className="w-6 h-6" />
                    </button>

                    {/* Receipt Content */}
                    <div className="p-8 border-b-2 border-dashed border-gray-200 bg-gray-50 text-center">
                        <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                            <CheckCircle className="w-8 h-8 text-green-600" />
                        </div>
                        <h2 className="text-2xl font-bold text-gray-900 mb-1">Payment Success</h2>
                        <p className="text-sm text-gray-500">Transaction #{data.id}</p>
                    </div>

                    <div className="p-8 space-y-6">
                        <div className="text-center mb-6">
                            <p className="text-gray-500 uppercase text-xs tracking-widest mb-1">Total Amount Paid</p>
                            <h1 className="text-4xl font-bold text-gray-900">₹{data.amount}</h1>
                        </div>

                        <div className="space-y-4 text-sm border-t border-gray-100 pt-6">
                            <div className="flex justify-between">
                                <span className="text-gray-500">Student Name</span>
                                <span className="font-bold text-gray-900">{data.studentName}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-gray-500">Class & Roll</span>
                                <span className="font-bold text-gray-900">{data.class} (Roll: {data.rollNo})</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-gray-500">Date</span>
                                <span className="font-bold text-gray-900">{new Date(data.paymentDate).toLocaleDateString()}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-gray-500">Payment Mode</span>
                                <span className="font-bold text-gray-900">{data.paymentMode}</span>
                            </div>
                            {data.remarks && (
                                <div className="flex justify-between">
                                    <span className="text-gray-500">Remarks</span>
                                    <span className="font-bold text-gray-900 text-right">{data.remarks}</span>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Action Buttons (Hidden on Print) */}
                    <div className="p-6 bg-gray-50 flex gap-3 print:hidden">
                        <button onClick={handlePrint} className="flex-1 bg-black text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-gray-800 transition-colors">
                            <Printer className="w-4 h-4" /> Print Receipt
                        </button>
                    </div>

                    {/* Footer for Print */}
                    <div className="hidden print:block text-center mt-12 text-xs text-gray-400">
                        <p>Generated by Student Management System</p>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
}
